### ISSUE TITLE
SCP-049-2 bugging ID-Card

### ISSUE THREAD

**Issue by CheddarSniffer** [civilnetworks-projects/SCP_Public_Development#29]
Grab the disguise of someone before they turn into 049-2, when they turn into an 049-2 and you swap to their disguise, who woulda guessed it, you are now a zombie but not really

**Comment by Kw1ll** [comment]
When you disguise as a player, and they get turned to a zombie it resets your disguise kit so you no longer have any disguise. 

Whilst testing this, I also found that you can disguise as surface characters like "Heavy Gun Dealer", swap to "Doctor" on foundation, and then instead of you having heavy gun dealer you are now a doctor instead.
