### ISSUE TITLE
Deployment Spot & E-11 Secondary Spawn

### ISSUE THREAD

**Issue by Rushi123456** [civilnetworks-projects/SCP_Public_Development#432]
This is in regards of the E-11 Secondary Spawn that is suppose to be in the old E-11 bunks. However, current deployment spot radius is too big for them to only spawn in that room, and they are now spawning randomly across LCZ & Security Sector stairs.

Just made this ticket to reduce the deployment spot radius and after that is done, to add the Deployment Spot to E-11.

**Comment by McYeke** [comment]
This is something that requires the radius of deployment zones to be lowered or reconfiguration to set deployment zones like we set permaprop regions by creating a square and assigning the "named" value to vjobeditor so they can spawn inside that square radius only.

**Comment by auburncivilnetworks** [comment]
While this is still in the works, Staff and GMs have been using the GMTP tool to create a one way link from E-11 bunks to SS.

**Comment by auburncivilnetworks** [comment]
This has been solved by careful positioning of the deployment zone to only encompass E-11 bunks as a valid spot. This deployment spot must be placed with the player positioned at exactly -5532 -1788 -9910.


Explanation:
This works by blocking off the target area and placing down a test zone (this is best done on the dev server). By blocking off the target area, you will spawn at every valid spot outside of where you want the group to spawn. 
The next step is to move the spot somewhere else that you think will be better, and repeat. If on one of these tries you spawn at 0,0,0 (the map's default spawn), that means that there is no valid spot that you can spawn at when selecting the deploy zone.
Next, you remove the props blocking the target area. If you spawn in the target area then you have a guaranteed reliable deploy zone. 

This spot is reliable because if there was any valid spot outside of the target area, you would've been put there when the target area was blocked off. The target spot is therefore the only valid spawn location for the deployment zone.
