### ISSUE TITLE
A-1 CO office window blinds don't work.

### ISSUE THREAD

**Issue by JackKincaed** [civilnetworks-projects/SCP_Public_Development#524]
(https://imgur.com/a/l9DglK2)

The button does not close or open the blinds.

**Comment by Freezgam03** [comment]
@JackKincaed This happens because the scanner to the right of it deletes any func_button entities near it. Just keep this in mind, I will move the scanner so this won't be the case anymore and it will work again after restart.



![Image](https://github.com/civilnetworks-projects/SCP_Public_Development/assets/65787083/402523f2-28ff-41db-a4d7-9654c150b319)
